name: im-react-helloworld
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: eks-delivery.aws.main.edp.projects.epam.com

database:
  required: false


ingress:
  required: false

image:
  name: im-react-helloworld
  version: latest